In [6]:
class a:
    def fun1(self):
        print("class a")
class b(a):
    def fun1(self):
        a.fun1(self)
        print("class b")
    def fun3(self):
        print("class b")
obj=b()
obj.fun1()

class b


In [19]:
#compare two complex number using operaator overloading of (<) operater
class complexNumber:
    def __init__(self,real,imaginary):
        self.real=real
        self.imaginary=imaginary
    def __lt__(self,other):
        if self.real<other.real:
            return True
        elif self.real==other.real:
            if self.imaginary<other.imaginary:
                return True
            else:
                return False
        else:
            return False
comp=complexNumber(1,2)
comp1=complexNumber(3,4)
print(comp.__lt__(comp1))
print(comp1<comp)

True
False


In [18]:
class complexNumber:
    def __init__(self,real,imaginary):
        self.real=real
        self.imaginary=imaginary
    def __add__(self,other):
        x=self.real+other.real
        y=self.imaginary+other.imaginary
        print("addition:",x,"+j",y)
o1=complexNumber(1,2)
o2=complexNumber(3,4)
print(o1+o2)

addition: 4 +j 6
None


In [ ]:
# from abc import ABC,abstractmethod
class polygon(ABC):
    @abstractmethod
    def noofsides(self):
        pass
class triangle(polygon):
    def noofsides(self):
        print("3 sides")
class pentagon(polygon):
    def noofsides(self):
        print("5 sides")
o1=triangle()
o1.noofsides()
o2=pentagon()
o2.noofsides()

# PB-657

In [9]:
from abc import ABC
class Employee(ABC):
    def __init__(self):
        self.emp_id=0
        self.name=""
        self.salary=0
    def get_Employee_details(self):
        self.emp_id=int(input("emp id:"))
        self.name=input("emp name:")
        self.salary=float(input("enter basic salary:"))
    def emp_id(self):
        pass
    def return_salary(self):
        return self.salary
    def print_employee_details(self):
        print("employee id:",self.emp_id)
        print("employee name:",self.name)
        print("employee salary:",self.salary)
class perks:
    def  __init__(self,basic_salary):
        self.basic_salary=basic_salary
        self.da=35
        self.hra=17
        self.pf=12
    def calculate_perks(self):
        self.da_final=(self.da*self.salary)/100
        self.hra_final=(self.hra*self.salary)/100
        self.pf_final=(self.pf*self.salary)/100
    def print_perks(self):
        print("DA:",self.da_final)
        print("HRA:",self.hra_final)
        print("PF:",self.pf_final)
        print("total perks:",self.da_final+self.hra_final-self.pf_final)
class netsalary(Employee,perks):
    def __init__(self):
        Employee.__init__(self)
        perks.__init__(self,self.salary)
    def emp_id(self):
        return self.emp.id
    def calculate_net_salary(self):
        self.calculate_perks()
        net_salary=(self.salary+self.da_final+self.hra_final-self.pf_final)
        return net_salary
    def print_salary_details(self):
        self.print_employee_details()
        self.print_perks()
        net_salary=self.calculate_net_salary()
        print("total salary:",net_salary)
employee=netsalary()
employee.get_Employee_details()
employee.calculate_net_salary()
employee.print_salary_details()

    
        
        
        
        
        

emp id:1
emp name:ewewfef
enter basic salary:25000
employee id: 1
employee name: ewewfef
employee salary: 25000.0
DA: 8750.0
HRA: 4250.0
PF: 3000.0
total perks: 10000.0
total salary: 35000.0


# Numpy

In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [12]:
arr1=np.array((1,2,3))
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [17]:
arr=np.array(42)
print(arr)
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

42
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
2
3


In [19]:
arr=np.array([1,2,3],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3]]]]]
5


In [20]:
arr=np.array([1,2,3])
print(arr[0]+arr[2])

4


In [21]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1[0,1])
print(arr1[1,3])

2
9


In [33]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr2[0,1,2])
print(arr2[1,1,-2])

6
11


In [34]:
arr=np.array([1,2,3,4,5,6])
print(arr[::2])

[1 3 5]


In [4]:
#2d array
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])
print(arr[1,3])
print(arr.shape)


2
9
(2, 5)


In [3]:
#3d array
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr2[1,1,0])
print(arr2.shape)

10
(2, 2, 3)


In [6]:
#array slicing
#start:end:step
#1D array slicing
arr=np.array([1,2,3,4,5])
print(arr[::2])

[1 3 5]


In [12]:
#2D array slicing
arr1=np.array([[1,2,3,4,5,6],[6,7,8,9,7,8]])
print(arr1[:1,1:6:2])




[[2 4 6]]


In [37]:
#3D array slicing
arr2=np.array([[[1,2,3,11],[4,5,6,12]],[[7,8,9,13],[10,11,12,14]]],ndmin=5)
print(arr2.shape)
print(arr2[:1,::1,1:3:])

(1, 1, 2, 2, 4)
[[[[[ 7  8  9 13]
    [10 11 12 14]]]]]


In [35]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [ ]:
#array reshaping
[]